import Link from "next/link";
import "./globals.scss";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Prueba",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul
            style={{
              display: "flex",
              justifyContent: "space-evenly",
              margin: "2rem 0",
              borderWidth: "3px",
              padding: "1rem 0",
            }}
          >
            <Link href={"/"}>Home</Link>
            <Link href={"/about"}>About</Link>
            <Link href={"/tienda"}>Tienda</Link>
            <Link href={"/posts"}>Posts</Link>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
