import Link from "next/link";
import "./globals.scss";
import { Inter } from "next/font/google";
import ThemeProvider from "@/context/ThemeContext";
import ToggleThemeButton from "@/components/ToggleThemeButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Prueba",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={inter.className}>
          <header>
            <ToggleThemeButton />
          </header>
          <nav>
            <ul
              style={{
                display: "flex",
                justifyContent: "space-evenly",
                margin: "1rem 0",
                border: "1px solid",
                padding: "1rem 0",
              }}
            >
              <Link href={"/"}>Home</Link>
              <Link href={"/about"}>About</Link>
              <Link href={"/tienda"}>Tienda</Link>
              <Link href={"/posts"}>Posts</Link>
            </ul>
          </nav>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
